#include "class_id.h"
#include "globals.h"
#include "dart_ver.h"

intptr_t kIllegalCid;
intptr_t kNativePointer;
intptr_t kFreeListElement;
intptr_t kForwardingCorpse;
intptr_t kObjectCid;
intptr_t kClassCid;
intptr_t kPatchClassCid;
intptr_t kFunctionCid;
intptr_t kTypeParametersCid;
intptr_t kClosureDataCid;
intptr_t kFfiTrampolineDataCid;
intptr_t kFieldCid;
intptr_t kScriptCid;
intptr_t kLibraryCid;
intptr_t kNamespaceCid;
intptr_t kKernelProgramInfoCid;
intptr_t kWeakSerializationReferenceCid;
intptr_t kCodeCid;
intptr_t kInstructionsCid;
intptr_t kInstructionsSectionCid;
intptr_t kInstructionsTableCid;
intptr_t kObjectPoolCid;
intptr_t kPcDescriptorsCid;
intptr_t kCodeSourceMapCid;
intptr_t kCompressedStackMapsCid;
intptr_t kLocalVarDescriptorsCid;
intptr_t kExceptionHandlersCid;
intptr_t kContextCid;
intptr_t kContextScopeCid;
intptr_t kSentinelCid;
intptr_t kSingleTargetCacheCid;
intptr_t kUnlinkedCallCid;
intptr_t kMonomorphicSmiableCallCid;
intptr_t kCallSiteDataCid;
intptr_t kICDataCid;
intptr_t kMegamorphicCacheCid;
intptr_t kSubtypeTestCacheCid;
intptr_t kLoadingUnitCid;
intptr_t kErrorCid;
intptr_t kApiErrorCid;
intptr_t kLanguageErrorCid;
intptr_t kUnhandledExceptionCid;
intptr_t kUnwindErrorCid;
intptr_t kInstanceCid;
intptr_t kLibraryPrefixCid;
intptr_t kTypeArgumentsCid;
intptr_t kAbstractTypeCid;
intptr_t kTypeCid;
intptr_t kFunctionTypeCid;
intptr_t kRecordTypeCid;
intptr_t kTypeRefCid;
intptr_t kTypeParameterCid;
intptr_t kFinalizerBaseCid;
intptr_t kFinalizerCid;
intptr_t kNativeFinalizerCid;
intptr_t kFinalizerEntryCid;
intptr_t kClosureCid;
intptr_t kNumberCid;
intptr_t kIntegerCid;
intptr_t kSmiCid;
intptr_t kMintCid;
intptr_t kDoubleCid;
intptr_t kBoolCid;
intptr_t kFloat32x4Cid;
intptr_t kInt32x4Cid;
intptr_t kFloat64x2Cid;
intptr_t kRecordCid;
intptr_t kTypedDataBaseCid;
intptr_t kTypedDataCid;
intptr_t kExternalTypedDataCid;
intptr_t kTypedDataViewCid;
intptr_t kPointerCid;
intptr_t kDynamicLibraryCid;
intptr_t kCapabilityCid;
intptr_t kReceivePortCid;
intptr_t kSendPortCid;
intptr_t kStackTraceCid;
intptr_t kSuspendStateCid;
intptr_t kRegExpCid;
intptr_t kWeakPropertyCid;
intptr_t kWeakReferenceCid;
intptr_t kMirrorReferenceCid;
intptr_t kLinkedHashMapCid;
intptr_t kFutureOrCid;
intptr_t kUserTagCid;
intptr_t kTransferableTypedDataCid;
intptr_t kMapCid;
intptr_t kConstMapCid;
intptr_t kSetCid;
intptr_t kConstSetCid;
intptr_t kArrayCid;
intptr_t kImmutableArrayCid;
intptr_t kGrowableObjectArrayCid;
intptr_t kStringCid;
intptr_t kOneByteStringCid;
intptr_t kTwoByteStringCid;
intptr_t kExternalOneByteStringCid;
intptr_t kExternalTwoByteStringCid;
intptr_t kFfiPointerCid;
intptr_t kFfiNativeFunctionCid;
intptr_t kFfiInt8Cid;
intptr_t kFfiInt16Cid;
intptr_t kFfiInt32Cid;
intptr_t kFfiInt64Cid;
intptr_t kFfiUint8Cid;
intptr_t kFfiUint16Cid;
intptr_t kFfiUint32Cid;
intptr_t kFfiUint64Cid;
intptr_t kFfiIntPtrCid;
intptr_t kFfiFloatCid;
intptr_t kFfiDoubleCid;
intptr_t kFfiVoidCid;
intptr_t kFfiHandleCid;
intptr_t kFfiBoolCid;
intptr_t kFfiNativeTypeCid;
intptr_t kFfiDynamicLibraryCid;
intptr_t kFfiStructCid;
intptr_t kTypedDataInt8ArrayCid;
intptr_t kTypedDataInt8ArrayViewCid;
intptr_t kExternalTypedDataInt8ArrayCid;
intptr_t kUnmodifiableTypedDataInt8ArrayViewCid;
intptr_t kTypedDataUint8ArrayCid;
intptr_t kTypedDataUint8ArrayViewCid;
intptr_t kExternalTypedDataUint8ArrayCid;
intptr_t kUnmodifiableTypedDataUint8ArrayViewCid;
intptr_t kTypedDataUint8ClampedArrayCid;
intptr_t kTypedDataUint8ClampedArrayViewCid;
intptr_t kExternalTypedDataUint8ClampedArrayCid;
intptr_t kUnmodifiableTypedDataUint8ClampedArrayViewCid;
intptr_t kTypedDataInt16ArrayCid;
intptr_t kTypedDataInt16ArrayViewCid;
intptr_t kExternalTypedDataInt16ArrayCid;
intptr_t kUnmodifiableTypedDataInt16ArrayViewCid;
intptr_t kTypedDataUint16ArrayCid;
intptr_t kTypedDataUint16ArrayViewCid;
intptr_t kExternalTypedDataUint16ArrayCid;
intptr_t kUnmodifiableTypedDataUint16ArrayViewCid;
intptr_t kTypedDataInt32ArrayCid;
intptr_t kTypedDataInt32ArrayViewCid;
intptr_t kExternalTypedDataInt32ArrayCid;
intptr_t kUnmodifiableTypedDataInt32ArrayViewCid;
intptr_t kTypedDataUint32ArrayCid;
intptr_t kTypedDataUint32ArrayViewCid;
intptr_t kExternalTypedDataUint32ArrayCid;
intptr_t kUnmodifiableTypedDataUint32ArrayViewCid;
intptr_t kTypedDataInt64ArrayCid;
intptr_t kTypedDataInt64ArrayViewCid;
intptr_t kExternalTypedDataInt64ArrayCid;
intptr_t kUnmodifiableTypedDataInt64ArrayViewCid;
intptr_t kTypedDataUint64ArrayCid;
intptr_t kTypedDataUint64ArrayViewCid;
intptr_t kExternalTypedDataUint64ArrayCid;
intptr_t kUnmodifiableTypedDataUint64ArrayViewCid;
intptr_t kTypedDataFloat32ArrayCid;
intptr_t kTypedDataFloat32ArrayViewCid;
intptr_t kExternalTypedDataFloat32ArrayCid;
intptr_t kUnmodifiableTypedDataFloat32ArrayViewCid;
intptr_t kTypedDataFloat64ArrayCid;
intptr_t kTypedDataFloat64ArrayViewCid;
intptr_t kExternalTypedDataFloat64ArrayCid;
intptr_t kUnmodifiableTypedDataFloat64ArrayViewCid;
intptr_t kTypedDataFloat32x4ArrayCid;
intptr_t kTypedDataFloat32x4ArrayViewCid;
intptr_t kExternalTypedDataFloat32x4ArrayCid;
intptr_t kUnmodifiableTypedDataFloat32x4ArrayViewCid;
intptr_t kTypedDataInt32x4ArrayCid;
intptr_t kTypedDataInt32x4ArrayViewCid;
intptr_t kExternalTypedDataInt32x4ArrayCid;
intptr_t kUnmodifiableTypedDataInt32x4ArrayViewCid;
intptr_t kTypedDataFloat64x2ArrayCid;
intptr_t kTypedDataFloat64x2ArrayViewCid;
intptr_t kExternalTypedDataFloat64x2ArrayCid;
intptr_t kUnmodifiableTypedDataFloat64x2ArrayViewCid;
intptr_t kByteDataViewCid;
intptr_t kUnmodifiableByteDataViewCid;
intptr_t kByteBufferCid;
intptr_t kNullCid;
intptr_t kDynamicCid;
intptr_t kVoidCid;
intptr_t kNeverCid;
intptr_t kNumPredefinedCids;

bool initClassId_2_1_2()
{
	kIllegalCid = 0;
	kFreeListElement = 1;
	kForwardingCorpse = 2;
	kObjectCid = 3;
	kClassCid = 4;
	kPatchClassCid = 5;
	kFunctionCid = 6;
	kClosureDataCid = 7;
	kFfiTrampolineDataCid = 8;
	kFieldCid = 9;
	kScriptCid = 10;
	kLibraryCid = 11;
	kNamespaceCid = 12;
	kKernelProgramInfoCid = 13;
	kCodeCid = 14;
	kInstructionsCid = 15;
	kInstructionsSectionCid = 16;
	kObjectPoolCid = 17;
	kPcDescriptorsCid = 18;
	kCodeSourceMapCid = 19;
	kCompressedStackMapsCid = 20;
	kLocalVarDescriptorsCid = 21;
	kExceptionHandlersCid = 22;
	kContextCid = 23;
	kContextScopeCid = 24;
	kSingleTargetCacheCid = 25;
	kUnlinkedCallCid = 26;
	kMonomorphicSmiableCallCid = 27;
	kCallSiteDataCid = 28;
	kICDataCid = 29;
	kMegamorphicCacheCid = 30;
	kSubtypeTestCacheCid = 31;
	kLoadingUnitCid = 32;
	kErrorCid = 33;
	kApiErrorCid = 34;
	kLanguageErrorCid = 35;
	kUnhandledExceptionCid = 36;
	kUnwindErrorCid = 37;
	kInstanceCid = 38;
	kLibraryPrefixCid = 39;
	kTypeArgumentsCid = 40;
	kAbstractTypeCid = 41;
	kTypeCid = 42;
	kFunctionTypeCid = 43;
	kTypeRefCid = 44;
	kTypeParameterCid = 45;
	kClosureCid = 46;
	kNumberCid = 47;
	kIntegerCid = 48;
	kSmiCid = 49;
	kMintCid = 50;
	kDoubleCid = 51;
	kBoolCid = 52;
	kGrowableObjectArrayCid = 53;
	kFloat32x4Cid = 54;
	kInt32x4Cid = 55;
	kFloat64x2Cid = 56;
	kTypedDataBaseCid = 57;
	kTypedDataCid = 58;
	kExternalTypedDataCid = 59;
	kTypedDataViewCid = 60;
	kPointerCid = 61;
	kDynamicLibraryCid = 62;
	kCapabilityCid = 63;
	kReceivePortCid = 64;
	kSendPortCid = 65;
	kStackTraceCid = 66;
	kRegExpCid = 67;
	kWeakPropertyCid = 68;
	kMirrorReferenceCid = 69;
	kLinkedHashMapCid = 70;
	kFutureOrCid = 71;
	kUserTagCid = 72;
	kTransferableTypedDataCid = 73;
	kWeakSerializationReferenceCid = 74;
	kArrayCid = 75;
	kImmutableArrayCid = 76;
	kStringCid = 77;
	kOneByteStringCid = 78;
	kTwoByteStringCid = 79;
	kExternalOneByteStringCid = 80;
	kExternalTwoByteStringCid = 81;
	kFfiPointerCid = 82;
	kFfiNativeFunctionCid = 83;
	kFfiInt8Cid = 84;
	kFfiInt16Cid = 85;
	kFfiInt32Cid = 86;
	kFfiInt64Cid = 87;
	kFfiUint8Cid = 88;
	kFfiUint16Cid = 89;
	kFfiUint32Cid = 90;
	kFfiUint64Cid = 91;
	kFfiIntPtrCid = 92;
	kFfiFloatCid = 93;
	kFfiDoubleCid = 94;
	kFfiVoidCid = 95;
	kFfiHandleCid = 96;
	kFfiNativeTypeCid = 97;
	kFfiDynamicLibraryCid = 98;
	kFfiStructCid = 99;
	kTypedDataInt8ArrayCid = 100;
	kTypedDataInt8ArrayViewCid = 101;
	kExternalTypedDataInt8ArrayCid = 102;
	kTypedDataUint8ArrayCid = 103;
	kTypedDataUint8ArrayViewCid = 104;
	kExternalTypedDataUint8ArrayCid = 105;
	kTypedDataUint8ClampedArrayCid = 106;
	kTypedDataUint8ClampedArrayViewCid = 107;
	kExternalTypedDataUint8ClampedArrayCid = 108;
	kTypedDataInt16ArrayCid = 109;
	kTypedDataInt16ArrayViewCid = 110;
	kExternalTypedDataInt16ArrayCid = 111;
	kTypedDataUint16ArrayCid = 112;
	kTypedDataUint16ArrayViewCid = 113;
	kExternalTypedDataUint16ArrayCid = 114;
	kTypedDataInt32ArrayCid = 115;
	kTypedDataInt32ArrayViewCid = 116;
	kExternalTypedDataInt32ArrayCid = 117;
	kTypedDataUint32ArrayCid = 118;
	kTypedDataUint32ArrayViewCid = 119;
	kExternalTypedDataUint32ArrayCid = 120;
	kTypedDataInt64ArrayCid = 121;
	kTypedDataInt64ArrayViewCid = 122;
	kExternalTypedDataInt64ArrayCid = 123;
	kTypedDataUint64ArrayCid = 124;
	kTypedDataUint64ArrayViewCid = 125;
	kExternalTypedDataUint64ArrayCid = 126;
	kTypedDataFloat32ArrayCid = 127;
	kTypedDataFloat32ArrayViewCid = 128;
	kExternalTypedDataFloat32ArrayCid = 129;
	kTypedDataFloat64ArrayCid = 130;
	kTypedDataFloat64ArrayViewCid = 131;
	kExternalTypedDataFloat64ArrayCid = 132;
	kTypedDataFloat32x4ArrayCid = 133;
	kTypedDataFloat32x4ArrayViewCid = 134;
	kExternalTypedDataFloat32x4ArrayCid = 135;
	kTypedDataInt32x4ArrayCid = 136;
	kTypedDataInt32x4ArrayViewCid = 137;
	kExternalTypedDataInt32x4ArrayCid = 138;
	kTypedDataFloat64x2ArrayCid = 139;
	kTypedDataFloat64x2ArrayViewCid = 140;
	kExternalTypedDataFloat64x2ArrayCid = 141;
	kByteDataViewCid = 142;
	kByteBufferCid = 143;
	kNullCid = 144;
	kDynamicCid = 145;
	kVoidCid = 146;
	kNeverCid = 147;
	kNumPredefinedCids = 148;
	return true;
}

bool initClassId_3_0_0()
{
	kIllegalCid = 0;
	kNativePointer = 1;
	kFreeListElement = 2;
	kForwardingCorpse = 3;
	kObjectCid = 4;
	kClassCid = 5;
	kPatchClassCid = 6;
	kFunctionCid = 7;
	kTypeParametersCid = 8;
	kClosureDataCid = 9;
	kFfiTrampolineDataCid = 10;
	kFieldCid = 11;
	kScriptCid = 12;
	kLibraryCid = 13;
	kNamespaceCid = 14;
	kKernelProgramInfoCid = 15;
	kWeakSerializationReferenceCid = 16;
	kCodeCid = 17;
	kInstructionsCid = 18;
	kInstructionsSectionCid = 19;
	kInstructionsTableCid = 20;
	kObjectPoolCid = 21;
	kPcDescriptorsCid = 22;
	kCodeSourceMapCid = 23;
	kCompressedStackMapsCid = 24;
	kLocalVarDescriptorsCid = 25;
	kExceptionHandlersCid = 26;
	kContextCid = 27;
	kContextScopeCid = 28;
	kSentinelCid = 29;
	kSingleTargetCacheCid = 30;
	kUnlinkedCallCid = 31;
	kMonomorphicSmiableCallCid = 32;
	kCallSiteDataCid = 33;
	kICDataCid = 34;
	kMegamorphicCacheCid = 35;
	kSubtypeTestCacheCid = 36;
	kLoadingUnitCid = 37;
	kErrorCid = 38;
	kApiErrorCid = 39;
	kLanguageErrorCid = 40;
	kUnhandledExceptionCid = 41;
	kUnwindErrorCid = 42;
	kInstanceCid = 43;
	kLibraryPrefixCid = 44;
	kTypeArgumentsCid = 45;
	kAbstractTypeCid = 46;
	kTypeCid = 47;
	kFunctionTypeCid = 48;
	kRecordTypeCid = 49;
	kTypeRefCid = 50;
	kTypeParameterCid = 51;
	kFinalizerBaseCid = 52;
	kFinalizerCid = 53;
	kNativeFinalizerCid = 54;
	kFinalizerEntryCid = 55;
	kClosureCid = 56;
	kNumberCid = 57;
	kIntegerCid = 58;
	kSmiCid = 59;
	kMintCid = 60;
	kDoubleCid = 61;
	kBoolCid = 62;
	kFloat32x4Cid = 63;
	kInt32x4Cid = 64;
	kFloat64x2Cid = 65;
	kRecordCid = 66;
	kTypedDataBaseCid = 67;
	kTypedDataCid = 68;
	kExternalTypedDataCid = 69;
	kTypedDataViewCid = 70;
	kPointerCid = 71;
	kDynamicLibraryCid = 72;
	kCapabilityCid = 73;
	kReceivePortCid = 74;
	kSendPortCid = 75;
	kStackTraceCid = 76;
	kSuspendStateCid = 77;
	kRegExpCid = 78;
	kWeakPropertyCid = 79;
	kWeakReferenceCid = 80;
	kMirrorReferenceCid = 81;
	kFutureOrCid = 82;
	kUserTagCid = 83;
	kTransferableTypedDataCid = 84;
	kMapCid = 85;
	kConstMapCid = 86;
	kSetCid = 87;
	kConstSetCid = 88;
	kArrayCid = 89;
	kImmutableArrayCid = 90;
	kGrowableObjectArrayCid = 91;
	kStringCid = 92;
	kOneByteStringCid = 93;
	kTwoByteStringCid = 94;
	kExternalOneByteStringCid = 95;
	kExternalTwoByteStringCid = 96;
	kFfiNativeFunctionCid = 97;
	kFfiInt8Cid = 98;
	kFfiInt16Cid = 99;
	kFfiInt32Cid = 100;
	kFfiInt64Cid = 101;
	kFfiUint8Cid = 102;
	kFfiUint16Cid = 103;
	kFfiUint32Cid = 104;
	kFfiUint64Cid = 105;
	kFfiFloatCid = 106;
	kFfiDoubleCid = 107;
	kFfiVoidCid = 108;
	kFfiHandleCid = 109;
	kFfiBoolCid = 110;
	kFfiNativeTypeCid = 111;
	kFfiStructCid = 112;
	kTypedDataInt8ArrayCid = 113;
	kTypedDataInt8ArrayViewCid = 114;
	kExternalTypedDataInt8ArrayCid = 115;
	kUnmodifiableTypedDataInt8ArrayViewCid = 116;
	kTypedDataUint8ArrayCid = 117;
	kTypedDataUint8ArrayViewCid = 118;
	kExternalTypedDataUint8ArrayCid = 119;
	kUnmodifiableTypedDataUint8ArrayViewCid = 120;
	kTypedDataUint8ClampedArrayCid = 121;
	kTypedDataUint8ClampedArrayViewCid = 122;
	kExternalTypedDataUint8ClampedArrayCid = 123;
	kUnmodifiableTypedDataUint8ClampedArrayViewCid = 124;
	kTypedDataInt16ArrayCid = 125;
	kTypedDataInt16ArrayViewCid = 126;
	kExternalTypedDataInt16ArrayCid = 127;
	kUnmodifiableTypedDataInt16ArrayViewCid = 128;
	kTypedDataUint16ArrayCid = 129;
	kTypedDataUint16ArrayViewCid = 130;
	kExternalTypedDataUint16ArrayCid = 131;
	kUnmodifiableTypedDataUint16ArrayViewCid = 132;
	kTypedDataInt32ArrayCid = 133;
	kTypedDataInt32ArrayViewCid = 134;
	kExternalTypedDataInt32ArrayCid = 135;
	kUnmodifiableTypedDataInt32ArrayViewCid = 136;
	kTypedDataUint32ArrayCid = 137;
	kTypedDataUint32ArrayViewCid = 138;
	kExternalTypedDataUint32ArrayCid = 139;
	kUnmodifiableTypedDataUint32ArrayViewCid = 140;
	kTypedDataInt64ArrayCid = 141;
	kTypedDataInt64ArrayViewCid = 142;
	kExternalTypedDataInt64ArrayCid = 143;
	kUnmodifiableTypedDataInt64ArrayViewCid = 144;
	kTypedDataUint64ArrayCid = 145;
	kTypedDataUint64ArrayViewCid = 146;
	kExternalTypedDataUint64ArrayCid = 147;
	kUnmodifiableTypedDataUint64ArrayViewCid = 148;
	kTypedDataFloat32ArrayCid = 149;
	kTypedDataFloat32ArrayViewCid = 150;
	kExternalTypedDataFloat32ArrayCid = 151;
	kUnmodifiableTypedDataFloat32ArrayViewCid = 152;
	kTypedDataFloat64ArrayCid = 153;
	kTypedDataFloat64ArrayViewCid = 154;
	kExternalTypedDataFloat64ArrayCid = 155;
	kUnmodifiableTypedDataFloat64ArrayViewCid = 156;
	kTypedDataFloat32x4ArrayCid = 157;
	kTypedDataFloat32x4ArrayViewCid = 158;
	kExternalTypedDataFloat32x4ArrayCid = 159;
	kUnmodifiableTypedDataFloat32x4ArrayViewCid = 160;
	kTypedDataInt32x4ArrayCid = 161;
	kTypedDataInt32x4ArrayViewCid = 162;
	kExternalTypedDataInt32x4ArrayCid = 163;
	kUnmodifiableTypedDataInt32x4ArrayViewCid = 164;
	kTypedDataFloat64x2ArrayCid = 165;
	kTypedDataFloat64x2ArrayViewCid = 166;
	kExternalTypedDataFloat64x2ArrayCid = 167;
	kUnmodifiableTypedDataFloat64x2ArrayViewCid = 168;
	kByteDataViewCid = 169;
	kUnmodifiableByteDataViewCid = 170;
	kByteBufferCid = 171;
	kNullCid = 172;
	kDynamicCid = 173;
	kVoidCid = 174;
	kNeverCid = 175;
	kNumPredefinedCids = 176;

	return true;
}

bool InitClassId(DartVersion ver)
{
	switch (ver) {
	case Dart2_1_2:
		return initClassId_2_1_2();
	case Dart3_0_0:
		return initClassId_3_0_0();
	}
	return false;
}